config/routes.rb
Mocket::Application.routes.draw do
  root :to => 'pages#show', id: 'main'

  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/auth/failure', :to => 'sessions#failure'
  get '/logout', :to => 'sessions#destroy'
  get '/login' => redirect { '/auth/google_oauth2' }


  get '/dashboard', to: 'users#dashboard', as: "dashboard"
  post '/dashboard', to: 'users#new_song'
  get '/archives', to: 'users#archives', as: "archives"
  put '/posts/:id/archive', to: 'users#archive', as: "archive"
  get '/favorites', to: 'users#favorites', as: "favorites"
  put '/posts/:id/favorite', to: 'users#favorite', as: "favorite"
  delete '/posts/:id', to: 'users#destroy_song', as: "post"
  get "/posts/export", to: "users#export", as: "export"

  post '/api/song', to: 'users#new_api_song'
  get '/api/history', to: 'users#history', as: "history"

  get '/settings', to: 'settings#default', as: "settings"
  patch '/settings', to: 'settings#update'
  get '/settings/api', to: 'settings#api', as: "settings_api"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  email          :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#  invited        :boolean          default(FALSE)
#  default_player :string(255)
#  access_token   :string(255)
#

class User < ActiveRecord::Base

  validates :email, presence: true, uniqueness: { case_sensitive: false}
  validates :name, presence: true
  validates :access_token, uniqueness: { case_sensitive: true}, if: lambda { access_token.present? }

  has_many :authorizations, dependent: :destroy
  has_many :posts, dependent: :destroy

  after_create :update_token

  def photo
    authorizations.first.photo
  end

  def default_player
    read_attribute(:default_player) || 'youtube'
  end

  def update_token
    until update_attributes(access_token: generate_tracking_code(32));end
  end

  def history
    posts.length > 0 ?
      posts.pluck(:source_url, :song_url, :search).flatten.compact : []
  end

  private
  def generate_tracking_code(length=32)
    o =  [('a'..'z'),('A'..'Z')].map{|i| i.to_a}.flatten
    (0...length).map{ o[rand(o.length)] }.join + Time.now.to_i.to_s
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, except: [:new_api_song]
  skip_before_action :verify_authenticity_token, only: [:new_api_song, :history]
  before_action :authenticate_user_by_token, only: [:new_api_song, :history]
  before_filter :set_post, only: [:destroy_song, :archive,
    :favorite]
  before_action :counters, only: [:dashboard, :favorites, :archives]

  def archives
    @posts = current_user.posts.archives.page(params[:page])
    respond_to do |format|
      format.html { render 'users/dashboard' }
      format.json { render json: @posts, status: 200 }
    end
  end

  def archive
    @post.update_attributes(archived: !@post.archived)
    respond_to do |format|
      format.html { redirect_to dashboard_path, notice: 'Song was successfully (un)archived.' }
      format.json { render json: @post, status: 200 }
    end
  end

  def dashboard
    @posts = current_user.posts.current.page(params[:page])
  end

  def favorites
    @posts = current_user.posts.favorites.page(params[:page])
    respond_to do |format|
      format.html { render 'users/dashboard' }
      format.json { render json: @posts, status: 200 }
    end
  end

  def favorite
    @post.update_attributes(favorite: !@post.favorite)
    respond_to do |format|
      format.html { redirect_to dashboard_path, notice: 'Song was successfully (un)favorite.' }
      format.json { render json: @post, status: 200 }
    end
  end

  def destroy_song
    @post.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_path, notice: 'Song was successfully deleted.' }
      format.json { render json: @post, status: 200 }
    end
  end

  def new_song
    @post = current_user.posts.new(post_params)
    if @post.save
      respond_to do |format|
        format.html { redirect_to dashboard_path, notice: 'Song was successfully created.' }
        format.json { render json: @post, status: 200 }
      end
    else
      respond_to do |format|
        format.html { redirect_to dashboard_path, flash: {error: 'Missing search.'}  }
        format.json { render json: @post, status: 422}
      end
    end
  end

  def new_api_song
    post = @user.posts.new(post_params)
    if post.save
      render json: post, status: 200
    else
      render json: post, status: 422
    end
  end

  def history
    render json: @user.history, status: 200
  end

  def export
    posts = if params[:category] == "dashboard"
              current_user.posts.current
            elsif params[:category] == "favorites"
              current_user.posts.favorites
            else
              current_user.posts.archives
            end
    service = current_user.default_player
    links = Post.get_links(posts, 'spotify')
    if links.length > 0
      render text: links.join('</br>')
    else
      render text: '0 spotify songs'
    end
  end

  private
  def authenticate_user_by_token
    @user = User.find_by_access_token(params[:access_token])
    render json: nil, status: 401 and return unless @user
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params[:post].permit(:archive, :favorite, :search, :song_url,
      :source_url)
  end

  def counters
    @count = {
      favorites: current_user.posts.favorites.count,
      archives: current_user.posts.archives.count,
      current: current_user.posts.current.count
    }
  end
end

app/helpers/user_helper.rb
module UserHelper

  def select_default_player(option)
    (current_user.default_player || 'youtube') == option
  end
end

app/views/users/_post.html.slim
li.song.clearfix
  div.menu.row
    a.title.pull-left.col-md-5{href="#"}
      h3 #{song.full_name}
    .visible-xs
      button.actionbar-toggle.collapsed data-target=".action-container-collapse" data-toggle="collapse" type="button"
        span.icon-bar
        span.icon-bar
        span.icon-bar
    .col-sm-5.pull-right.action-container-collapse.navbar-collapse.collapse
      ul.action-container
        li.delete.action
          = link_to post_path(post), method: :delete do
            | Delete
        li.archive.action
          = link_to archive_path(post), method: :put do
            | #{post.archived ? 'Unarchive' : 'Archive'}
        li.favorite.action
          = link_to favorite_path(post), method: :put do
            | #{post.favorite ? 'Unfavorite' : 'Favorite'}
  .row.embed.margin-top
    .col-sm-8.col-md-offset-3.col-sm-offset-2.col-xs-12.col-md-6
      - song.services.each_with_index do |service, index|
        div class="service \
        #{song.services_names.include?(current_user.default_player) && \
          song.services.length > 1 && \
          service.name != current_user.default_player ? \
          'hide' : 'display'}"
            = raw service.html
      - if song.services.length == 0
        div.service.display
          .sad
            p
              | :(
  .row.tools.margin-top
    .col-sm-4.hidden-xs.tags
      - song.tags.each do |tag|
        .tag tag
    .col-sm-4.col-sm-offset-4.col-xs-12
      select.source-select.form-control.pull-right.js-source-select
        - song.services.each do |service|
          option{value="#{service.name}"
            selected=(select_default_player(service.name))}
            = service.name.capitalize
        - if song.services.length == 0
          option{value="0"} Nothing :(

app/views/users/_sidebar.html.slim
.sidebar-nav
  section.user-info
    a{href="#"}
      h1=current_user.name
  ul.nav-lists
    li class="nav-song-list  #{'active' if action_name == "dashboard"}"
      a{href="#{dashboard_path}"} Song list
      span.count.pull-right #{@count[:current] if @count[:current] > 0}
    li class="nav-favorite  #{'active' if action_name == "favorites"}"
      a{href="#{favorites_path}"} Favorites
      span.count.pull-right #{@count[:favorites] if @count[:favorites] > 0}
    li class="nav-archive  #{'active' if action_name == "archives"}"
      a{href="#{archives_path}"} Archives
      span.count.pull-right #{@count[:archives] if @count[:archives] > 0}

app/views/users/_sidebar_dashboard.html.slim
.sidebar-nav
  section.user-info
  ul.nav-lists
    li class="nav-song-list  #{'active' if action_name == "settings"}"
      a{href="#{settings_path}"} Account
    li class="nav-song-list  #{'active' if action_name == "api"}"
      a{href="#"} API

app/views/users/dashboard.html.slim
= content_for(:extra_body_classes, 'main-page')
= render 'header'
.container
  .row.row-offcanvas.row-offcanvas-left
    .col-xs-6.col-sm-3.sidebar-offcanvas#sidebar role="navigation"
      = render 'sidebar'
    .col-xs-12.col-sm-9
      div.visible-xs.toggle-canvas
        button.btn.btn-default.btn-xs.btn-offcanvas {data-toggle="offcanvas" type="button"} Toggle nav
      section.row.songs-container
        header.songs-controls.clearfix
          .col-xs-4.col-sm-4
            a.pull-left href="#{export_path(category: action_name)}" export as a spotify  playlist
          .col-xs-8.col-sm-offset-2.col-sm-6
            = form_tag(dashboard_path, method: :post, class: "add-post") do |f|
              .input-group.pull-right {type="text"}
                input.form-control.search#post_search name="post[search]"
                span.input-group-btn
                  button.btn.btn-default.add {type="submit"} Add
        ul.songs-list
          - @posts.each do |post|
            = render 'post', post: post, song: post.song
      .row
        .col-sm-12
          ul.pagination
            = will_paginate @posts

app/views/users/settings.html.slim
= content_for(:extra_body_classes, 'main-page')
= render 'header'
.container
  .row.row-offcanvas.row-offcanvas-left
    .col-xs-6.col-sm-3.sidebar-offcanvas#sidebar role="navigation"
      = render 'sidebar_dashboard'
    .col-xs-12.col-sm-9.main
      div.visible-xs.toggle-canvas
        button.btn.btn-default.btn-xs.btn-offcanvas {data-toggle="offcanvas" type="button"} Toggle nav
      = form_for(current_user, url: settings_path, method: :patch) do |f|
        .row.form-group
          .col-sm-3
            label{for="disabledTextInput"} Default player:
          .col-sm-6
            select.form-control name="user[default_player]"
              option{value="youtube" selected=(select_default_player('youtube'))} Youtube
              option{value="spotify" selected=(select_default_player('spotify'))} Spotify
        .row.save
          .col-sm-2.col-sm-offset-10
            = f.submit 'Save', class: 'btn'