config/routes.rb
Mocket::Application.routes.draw do
  root :to => 'pages#show', id: 'main'

  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/auth/failure', :to => 'sessions#failure'
  get '/logout', :to => 'sessions#destroy'
  get '/login' => redirect { '/auth/google_oauth2' }


  get '/dashboard', to: 'users#dashboard', as: "dashboard"
  post '/dashboard', to: 'users#new_song'
  get '/archives', to: 'users#archives', as: "archives"
  put '/posts/:id/archive', to: 'users#archive', as: "archive"
  get '/favorites', to: 'users#favorites', as: "favorites"
  put '/posts/:id/favorite', to: 'users#favorite', as: "favorite"
  delete '/posts/:id', to: 'users#destroy_song', as: "post"
  get "/posts/export", to: "users#export", as: "export"

  post '/api/song', to: 'users#new_api_song'
  get '/api/history', to: 'users#history', as: "history"

  get '/settings', to: 'settings#default', as: "settings"
  patch '/settings', to: 'settings#update'
  get '/settings/api', to: 'settings#api', as: "settings_api"

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :authenticate_user

  def default
  end

  def api
  end

  def update
    if current_user.update_attributes(user_params)
      respond_to do |format|
        format.html { redirect_to settings_path }
        format.json { render json: current_user, status: 200 }
      end
    else
      respond_to do |format|
        format.html { redirect_to settings_path, notice: 'There was a problem with update.' }
        format.json { render json: current_user, status: 422 }
      end
    end
  end

  private
  def user_params
    params[:user].permit(:default_player)
  end

end

app/views/settings/_sidebar.html.slim
.sidebar-nav
  section.user-info
  ul.nav-lists
    li class="nav-song-list  #{'active' if action_name == "default"}"
      a{href="#{settings_path}"} Account
    li class="nav-song-list  #{'active' if action_name == "api"}"
      a{href="#{settings_api_path}"} API

app/views/settings/api.html.slim
= content_for(:extra_body_classes, 'main-page')
= render 'header'
.container
  .row.row-offcanvas.row-offcanvas-left
    .col-xs-6.col-sm-3.sidebar-offcanvas#sidebar role="navigation"
      = render 'sidebar'
    .col-xs-12.col-sm-9.main
      div.visible-xs.toggle-canvas
        button.btn.btn-default.btn-xs.btn-offcanvas {data-toggle="offcanvas" type="button"} Toggle nav
      .row.form-group
        .col-sm-3
          label{for="api_token"} API TOKEN:
        .col-sm-6
          input#api_token.form-control {value="#{current_user.access_token}" disabled}

app/views/settings/default.html.slim
= content_for(:extra_body_classes, 'main-page')
= render 'header'
.container
  .row.row-offcanvas.row-offcanvas-left
    .col-xs-6.col-sm-3.sidebar-offcanvas#sidebar role="navigation"
      = render 'sidebar'
    .col-xs-12.col-sm-9.main
      div.visible-xs.toggle-canvas
        button.btn.btn-default.btn-xs.btn-offcanvas {data-toggle="offcanvas" type="button"} Toggle nav
      = form_for(current_user, url: settings_path, method: :patch) do |f|
        .row.form-group
          .col-sm-3
            label Default player:
          .col-sm-6
            select.form-control name="user[default_player]"
              option{value="youtube" selected=(select_default_player('youtube'))} Youtube
              option{value="spotify" selected=(select_default_player('spotify'))} Spotify
        .row.save
          .col-sm-2.col-sm-offset-10
            = f.submit 'Save', class: 'btn'