config/routes.rb
Mocket::Application.routes.draw do
  root :to => 'pages#show', id: 'main'

  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/auth/failure', :to => 'sessions#failure'
  get '/logout', :to => 'sessions#destroy'
  get '/login' => redirect { '/auth/google_oauth2' }


  get '/dashboard', to: 'users#dashboard', as: "dashboard"
  post '/dashboard', to: 'users#new_song'
  get '/archives', to: 'users#archives', as: "archives"
  put '/posts/:id/archive', to: 'users#archive', as: "archive"
  get '/favorites', to: 'users#favorites', as: "favorites"
  put '/posts/:id/favorite', to: 'users#favorite', as: "favorite"
  delete '/posts/:id', to: 'users#destroy_song', as: "post"
  get "/posts/export", to: "users#export", as: "export"

  post '/api/song', to: 'users#new_api_song'
  get '/api/history', to: 'users#history', as: "history"

  get '/settings', to: 'settings#default', as: "settings"
  patch '/settings', to: 'settings#update'
  get '/settings/api', to: 'settings#api', as: "settings_api"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  def authenticate_user
    redirect_to root_path and return unless signed_in?
    unless current_user.invited
      flash[:message] = "Currently access to the specific-user subpages is restricted."
      redirect_to root_path
    end
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def signed_in?
    !!current_user
  end
  helper_method :current_user, :signed_in?

  def current_user=(user)
    @current_user = user
    session[:user_id] = user.nil? ? user : user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def active?(*symbol)
    symbol.any? do |s|
      action_name == s.to_s || controller_name == s.to_s
    end
  end
end

app/views/application/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%= value %></div>
  <% end -%>
</div>

app/views/application/_footer.html.slim
div.footer
  p
    | Developed by
    a{href="http://www.arathunku.com"}  arathunku

app/views/application/_header.html.slim
header.navbar.navbar-hover
  .container
    .navbar-header
      button.navbar-toggle.collapsed {type="button" data-toggle="collapse" data-target=".navbar-collapse"}
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand {href="/"} Mocket
    nav.collapse.navbar-collapse {role="navigation"}
      ul.nav.navbar-nav.pull-right
        - if signed_in?
          li class=('active' if active?(:users))
            a{href="#{dashboard_path}"}Dashboard
          li class=('active' if active?(:settings))
            a{href="#{settings_path}"}Settings
          li
            a{href="#{logout_path}"}Logout
        - else
          li
            a#login{href="#{login_path}"}Log in with Google Account

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>